{% set name = "moab" %}
{% set version = "5.1.0" %}
{% set sha256 = "0371fc25d2594589e95700739f01614f097b6157fb6023ed8995e582726ca658" %}
{% set build = 5 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prioritize nompi variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/fathom/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `moab * mpi_mpich_*` for mpich
  # `moab * mpi_*` for any mpi
  # `moab * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

  {% if mpi != 'nompi' %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

  skip: True  # [win]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openssh  # [mpi == 'openmpi']
  host:
    - libblas
    - libcblas
    - python
    - hdf5 * {{ mpi_prefix }}_*
    - numpy
    - setuptools
    - cython
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - python
    - hdf5 * {{ mpi_prefix }}_*
    - numpy
    - setuptools
    - {{ mpi }}  # [mpi != 'nompi']
    - openssh  # [mpi == 'openmpi']

test:
  source_files:
    - MeshFiles/unittest/surfrandomtris-4part.h5m
    - examples/python/laplaciansmoother.py
  imports:
    - pymoab
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]
    - python examples/python/laplaciansmoother.py MeshFiles/unittest/surfrandomtris-4part.h5m 25

about:
  home: http://press3.mcs.anl.gov/sigma/moab-library/
  license: LGPL v2.1
  license_file: LICENSE
  summary: 'The Mesh-Oriented datABase'
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: http://press3.mcs.anl.gov/sigma/moab-library/
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - scopatz
    - vijaysm
    - iulian787
    - gonuke
    - xylar
