{% set name = "moab" %}
{% set version = "5.1.0" %}
{% set sha256 = "0371fc25d2594589e95700739f01614f097b6157fb6023ed8995e582726ca658" %}
{% set build = 6 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

# ensure tempest is defined (needed for conda-smithy recipe-lint)
{% set tempest = tempest or 'notempest' %}

{% if mpi == 'nompi' and tempest == 'notempest' %}
# prioritize nompi and notempest variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/fathom/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-missing-MPI_Finalize-to-imoab_coupler-test.patch

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi and tempest or notempest variants explicitly:
  # `moab * mpi_mpich_tempest_*` for mpich and tempest
  # `moab * mpi_*_tempest_*` for any mpi and tempest
  # `moab * nompi_tempest_*` for no mpi and tempest
  # `moab * mpi_mpich_notempest_*` for mpich and no tempest
  # `moab * mpi_*_notempest_*` for any mpi and no tempest
  # `moab * nompi_notempest_*` for no mpi and no tempest

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}__{{tempest}}_h{{ PKG_HASH }}_{{ build }}"

  {% if mpi != 'nompi' %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

  skip: True  # [win]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openssh  # [mpi == 'openmpi']
    - tempest-remap  # [tempest == 'tempest']
    - libnetcdf * {{ mpi_prefix }}_*  # [tempest == 'tempest']
    - eigen  # [tempest == 'tempest']
  host:
    - libblas
    - libcblas
    - python
    - hdf5 * {{ mpi_prefix }}_*
    - numpy
    - setuptools
    - cython
    - {{ mpi }}  # [mpi != 'nompi']
    - tempest-remap  # [tempest == 'tempest']
    - libnetcdf * {{ mpi_prefix }}_*  # [tempest == 'tempest']
  run:
    - python
    - hdf5 * {{ mpi_prefix }}_*
    - numpy
    - setuptools
    - {{ mpi }}  # [mpi != 'nompi']
    - openssh  # [mpi == 'openmpi']
    - tempest-remap  # [tempest == 'tempest']
    - libnetcdf * {{ mpi_prefix }}_*  # [tempest == 'tempest']

test:
  source_files:
    - MeshFiles/unittest/surfrandomtris-4part.h5m
    - examples/python/laplaciansmoother.py
  imports:
    - pymoab
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]
    - python examples/python/laplaciansmoother.py MeshFiles/unittest/surfrandomtris-4part.h5m 25

about:
  home: http://press3.mcs.anl.gov/sigma/moab-library/
  license: LGPL v2.1
  license_file: LICENSE
  summary: 'The Mesh-Oriented datABase'
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: http://press3.mcs.anl.gov/sigma/moab-library/
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - scopatz
    - vijaysm
    - iulian787
    - gonuke
    - xylar
