{% set name = "moab" %}
{% set version = "5.3.0rc2" %}
{% set build = 0 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

# ensure tempest is defined (needed for conda-smithy recipe-lint)
{% set tempest = tempest or 'notempest' %}

{% if mpi == 'nompi' and tempest == 'notempest' %}
# prioritize nompi and notempest variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # url: http://ftp.mcs.anl.gov/pub/fathom/{{ name }}-{{ version }}.tar.gz
  url: https://ftp.mcs.anl.gov/pub/fathom/moab-5.3.0-RC2.tar.gz
  sha256: 2691c2ff673706693d57354e8fa046857ab5b21197ac2200d63f72a0d8a28ec1
build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi and tempest or notempest variants explicitly:
  # `moab * mpi_mpich_tempest_*` for mpich and tempest
  # `moab * mpi_*_tempest_*` for any mpi and tempest
  # `moab * nompi_tempest_*` for no mpi and tempest
  # `moab * mpi_mpich_notempest_*` for mpich and no tempest
  # `moab * mpi_*_notempest_*` for any mpi and no tempest
  # `moab * nompi_notempest_*` for no mpi and no tempest

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_{{ tempest }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}"

  {% if mpi != 'nompi' %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

  skip: true  # [win or osx or py<39]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openssh  # [mpi == 'openmpi']
  host:
    - python
    #- cython
    #- eigen
    # need to list hdf5 and libnetcdf twice to get version
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    #- hdf5
    #- hdf5 * {{ mpi_prefix }}_*
    #- libblas
    #- liblapack
    #- libnetcdf  # [tempest == 'tempest']
    #- libnetcdf * {{ mpi_prefix }}_*  # [tempest == 'tempest']
    #- metis
    #- {{ mpi }}  # [mpi != 'nompi']
    #- numpy
    #- setuptools
    - tempest-remap 2.1.0  # [tempest == 'tempest']
    #- zoltan * {{ mpi_prefix }}_*   # [mpi != 'nompi']

  run:
    - python
    - hdf5 * {{ mpi_prefix }}_*
    - libblas
    - liblapack
    - libnetcdf * {{ mpi_prefix }}_*  # [tempest == 'tempest']
    - metis
    - {{ mpi }}  # [mpi != 'nompi']
    - numpy
    - openssh  # [mpi == 'openmpi']
    - setuptools
    - tempest-remap 2.1.0  # [tempest == 'tempest']
    - zoltan * {{ mpi_prefix }}_*   # [mpi != 'nompi']

test:
  source_files:
    - MeshFiles/unittest/surfrandomtris-4part.h5m
    - examples/python/laplaciansmoother.py
  imports:
    - pymoab
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]
    - python examples/python/laplaciansmoother.py MeshFiles/unittest/surfrandomtris-4part.h5m 25
    - mbtempest --help  # [tempest == 'tempest']

about:
  home: http://press3.mcs.anl.gov/sigma/moab-library/
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: The Mesh-Oriented datABase
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: http://press3.mcs.anl.gov/sigma/moab-library/
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - scopatz
    - vijaysm
    - iulian787
    - gonuke
    - xylar
