{% set name = "moab" %}
{% set version = "4.9.2" %}
{% set sha256 = "26611b8cc24f6b7df52eb4ecbd31523d61523da0524b5a2d066a7656e2e82ac5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/fathom/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - gcc  # [osx]
    - automake
    - libtool
    - mpich
    - hdf5 1.8.17|1.8.17.*
  run:
    - libgfortran  # [osx]
    - mpich
    - hdf5 1.8.17|1.8.17.*

test:
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]

about:
  home: http://press3.mcs.anl.gov/sigma/moab-library/
  license: LGPL v2.1
  license_file: LICENSE
  summary: 'The Mesh-Oriented datABase'
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: http://press3.mcs.anl.gov/sigma/moab-library/
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - scopatz
    - vijaysm
