{% set name = "moab" %}
{% set version = "5.0.0" %}
{% set sha256 = "df5d5eb8c0d0dbb046de2e60aa611f276cbf007c9226c44a24ed19c570244e64" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/fathom/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - gcc  # [unix]
    - automake
    - libtool
    - hdf5 1.10.1
  run:
    - libgfortran  # [osx]
    - hdf5 1.10.1

test:
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]

about:
  home: http://press3.mcs.anl.gov/sigma/moab-library/
  license: LGPL v2.1
  license_file: LICENSE
  summary: 'The Mesh-Oriented datABase'
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: http://press3.mcs.anl.gov/sigma/moab-library/
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - scopatz
    - vijaysm
