{% set name = "moab" %}
{% set version = "5.1.0" %}
{% set sha256 = "0371fc25d2594589e95700739f01614f097b6157fb6023ed8995e582726ca658" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/fathom/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  skip: True  # [win]

requirements:
  build:
    - automake
    - libtool
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - hdf5
    - numpy
    - setuptools
    - cython
  run:
    - python
    - hdf5
    - numpy
    - setuptools

test:
  source_files:
    - MeshFiles/unittest/surfrandomtris-4part.h5m
    - examples/python/laplaciansmoother.py
  imports:
    - pymoab
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]
    - python examples/python/laplaciansmoother.py MeshFiles/unittest/surfrandomtris-4part.h5m 25

about:
  home: http://press3.mcs.anl.gov/sigma/moab-library/
  license: LGPL v2.1
  license_file: LICENSE
  summary: 'The Mesh-Oriented datABase'
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: http://press3.mcs.anl.gov/sigma/moab-library/
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - scopatz
    - vijaysm
    - iulian787
    - gonuke
    - xylar
