{% set name = "moab" %}
{% set version = "5.5.1" %}
{% set build = 0 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

# ensure tempest is defined (needed for conda-smithy recipe-lint)
{% set tempest = tempest or 'notempest' %}

{% if mpi == 'nompi' and tempest == 'notempest' %}
# prioritize nompi and notempest variant via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://web.cels.anl.gov/projects/sigma/downloads/moab/moab-{{ version }}.tar.gz
  sha256: 67b6ed3a13c235cec16f60f8f46f9bf0371fd321cf36dea113d0e09f09d0d438
build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi and tempest or notempest variants explicitly:
  # `moab * mpi_mpich_tempest_*` for mpich and tempest
  # `moab * mpi_*_tempest_*` for any mpi and tempest
  # `moab * nompi_tempest_*` for no mpi and tempest
  # `moab * mpi_mpich_notempest_*` for mpich and no tempest
  # `moab * mpi_*_notempest_*` for any mpi and no tempest
  # `moab * nompi_notempest_*` for no mpi and no tempest

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_{{ tempest }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}

  {% if mpi != 'nompi' %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_{{ tempest }}_*
  {% endif %}

  skip: true  # [win]

requirements:
  build:
    - automake
    - libtool
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openssh  # [mpi == 'openmpi']
  host:
    - python
    - pip >=22.0
    - cython <3.0.0
    - eigen
    # need to list hdf5 and libnetcdf twice to get version
    # pinning from conda_build_config and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - libblas
    - liblapack
    - libnetcdf  # [tempest == 'tempest']
    - libnetcdf * {{ mpi_prefix }}_*  # [tempest == 'tempest']
    - metis
    - {{ mpi }}  # [mpi != 'nompi']
    - numpy
    - setuptools
    - tempest-remap >=2.2.0,<2.3.0  # [tempest == 'tempest']
    - zoltan * {{ mpi_prefix }}_*   # [mpi != 'nompi']

  run:
    - python
    - hdf5 * {{ mpi_prefix }}_*
    - libblas
    - liblapack
    - libnetcdf * {{ mpi_prefix }}_*  # [tempest == 'tempest']
    - metis
    - {{ mpi }}  # [mpi != 'nompi']
    - numpy
    - openssh  # [mpi == 'openmpi']
    - setuptools
    - tempest-remap >=2.2.0,<2.3.0  # [tempest == 'tempest']
    - zoltan * {{ mpi_prefix }}_*   # [mpi != 'nompi']

test:
  source_files:
    - MeshFiles/unittest/surfrandomtris-4part.h5m
    - examples/python/laplaciansmoother.py
  imports:
    - pymoab
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]
    - python examples/python/laplaciansmoother.py MeshFiles/unittest/surfrandomtris-4part.h5m 25
    - mbtempest --help  # [tempest == 'tempest']

about:
  home: https://sigma.mcs.anl.gov/moab-library
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: The Mesh-Oriented datABase
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: https://web.cels.anl.gov/projects/sigma/docs/moab
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - xylar
    - vijaysm
    - scopatz
    - iulian787
    - gonuke
