{% set name = "moab" %}
{% set version = "5.0.1" %}
{% set sha256 = "e405031b1bf5e22950c2e5ca4dbbdeecdb59a3bd0db46ec3975d9b39e487185f" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.mcs.anl.gov/pub/fathom/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - toolchain
    - gcc  # [unix]
    - automake
    - libtool
    - hdf5 1.10.1
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - numpy 1.11.*
    - setuptools
  run:
    - libgfortran  # [osx]
    - hdf5 1.10.1
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*

test:
  commands:
    - test -f ${PREFIX}/lib/libMOAB.so  # [linux]
    - test -f ${PREFIX}/lib/libMOAB.dylib  # [osx]

about:
  home: http://press3.mcs.anl.gov/sigma/moab-library/
  license: LGPL v2.1
  license_file: LICENSE
  summary: 'The Mesh-Oriented datABase'
  description: |
    The Mesh-Oriented datABase (MOAB) is a component for representing and
    evaluating mesh data. MOAB can store structured and unstructured mesh,
    consisting of elements in the finite element zoo plus polygons and
    polyhedra.
  doc_url: http://press3.mcs.anl.gov/sigma/moab-library/
  dev_url: https://bitbucket.org/fathomteam/moab.git

extra:
  recipe-maintainers:
    - scopatz
    - vijaysm
    - iulian787
