travis:
  secure:
    BINSTAR_TOKEN: q7TuEUHtqsbiZxIVhpmfg4yDodE3seMdbQDLPb+W3oKjcQ0Dgtdqc6Sok00gJTzJgw+9iiStzHyezJTjrD4UfjW1TSnFB2vCaShk45oSLrXnu18m3I1SnpopTBcHRpsdlgcJfJCzAwQW65kNbcK5CowRkXVUFGWIXBzR21zuKdbWZlNtP2qSIxakftXPU8DZkE9U82SrMCtrN8nVzWGnc9DQblEBxbBkftiabx4t2oGGgtV6q6A0OIGxwN2+9kSKLPB9qv3nSYL5ZBTxzS6L/T960taC+F1ZtO812FCGNRleoM2RZjH7cwdHHvBU7fRY4JvoXYY0M1P74Arx6W7IKsDIHt/XvBXMD//r8jK3hIf8YqPSbgDYYjU7mqqw2gdmN0dBHhi2TTgJFSTStsne3hxgsu3+mBr1r0xpYZkhCMIGFgCxKtE+fTs+9Fk9o9nIwmzX0qS3LFlduKLcp+3j+llnZEOwdGwuje+OPzqusO+Csvf03qYr4LiVZVXj0kLBFo11a+tLphHNk++2517Aul0jDxRtS9RuzukENIrvmpM0HgzuU3i1LyYrs1cMxGkQRV3KsmbQcZymdRiWzx9cJ+a8zKyUhcnoNCYCykkrrXM+mvd5TaNeOSDI+WevDW0ZXKj6hZ6Mj9+3QF/MK0wKmCq9PpUpHmbzuAUNFaOegGo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
