# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_mpimpichnumpy1.16python3.6.____cpythontempestnotempest:
        CONFIG: osx_64_mpimpichnumpy1.16python3.6.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpimpichnumpy1.16python3.6.____cpythontempesttempest:
        CONFIG: osx_64_mpimpichnumpy1.16python3.6.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpimpichnumpy1.16python3.7.____cpythontempestnotempest:
        CONFIG: osx_64_mpimpichnumpy1.16python3.7.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpimpichnumpy1.16python3.7.____cpythontempesttempest:
        CONFIG: osx_64_mpimpichnumpy1.16python3.7.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpimpichnumpy1.16python3.8.____cpythontempestnotempest:
        CONFIG: osx_64_mpimpichnumpy1.16python3.8.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpimpichnumpy1.16python3.8.____cpythontempesttempest:
        CONFIG: osx_64_mpimpichnumpy1.16python3.8.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpimpichnumpy1.18python3.6.____73_pypytempestnotempest:
        CONFIG: osx_64_mpimpichnumpy1.18python3.6.____73_pypytempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpimpichnumpy1.18python3.6.____73_pypytempesttempest:
        CONFIG: osx_64_mpimpichnumpy1.18python3.6.____73_pypytempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.16python3.6.____cpythontempestnotempest:
        CONFIG: osx_64_mpinompinumpy1.16python3.6.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.16python3.6.____cpythontempesttempest:
        CONFIG: osx_64_mpinompinumpy1.16python3.6.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.16python3.7.____cpythontempestnotempest:
        CONFIG: osx_64_mpinompinumpy1.16python3.7.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.16python3.7.____cpythontempesttempest:
        CONFIG: osx_64_mpinompinumpy1.16python3.7.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.16python3.8.____cpythontempestnotempest:
        CONFIG: osx_64_mpinompinumpy1.16python3.8.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.16python3.8.____cpythontempesttempest:
        CONFIG: osx_64_mpinompinumpy1.16python3.8.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.18python3.6.____73_pypytempestnotempest:
        CONFIG: osx_64_mpinompinumpy1.18python3.6.____73_pypytempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpinompinumpy1.18python3.6.____73_pypytempesttempest:
        CONFIG: osx_64_mpinompinumpy1.18python3.6.____73_pypytempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.16python3.6.____cpythontempestnotempest:
        CONFIG: osx_64_mpiopenmpinumpy1.16python3.6.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.16python3.6.____cpythontempesttempest:
        CONFIG: osx_64_mpiopenmpinumpy1.16python3.6.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.16python3.7.____cpythontempestnotempest:
        CONFIG: osx_64_mpiopenmpinumpy1.16python3.7.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.16python3.7.____cpythontempesttempest:
        CONFIG: osx_64_mpiopenmpinumpy1.16python3.7.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.16python3.8.____cpythontempestnotempest:
        CONFIG: osx_64_mpiopenmpinumpy1.16python3.8.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.16python3.8.____cpythontempesttempest:
        CONFIG: osx_64_mpiopenmpinumpy1.16python3.8.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.18python3.6.____73_pypytempestnotempest:
        CONFIG: osx_64_mpiopenmpinumpy1.18python3.6.____73_pypytempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_mpiopenmpinumpy1.18python3.6.____73_pypytempesttempest:
        CONFIG: osx_64_mpiopenmpinumpy1.18python3.6.____73_pypytempesttempest
        UPLOAD_PACKAGES: 'True'
    maxParallel: 8
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)