# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  timeoutInMinutes: 360
  strategy:
    maxParallel: 8
    matrix:
      osx_mpimpichpython3.6.____cpythontempestnotempest:
        CONFIG: osx_mpimpichpython3.6.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpimpichpython3.6.____cpythontempesttempest:
        CONFIG: osx_mpimpichpython3.6.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpimpichpython3.7.____cpythontempestnotempest:
        CONFIG: osx_mpimpichpython3.7.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpimpichpython3.7.____cpythontempesttempest:
        CONFIG: osx_mpimpichpython3.7.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpimpichpython3.8.____cpythontempestnotempest:
        CONFIG: osx_mpimpichpython3.8.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpimpichpython3.8.____cpythontempesttempest:
        CONFIG: osx_mpimpichpython3.8.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpinompipython3.6.____cpythontempestnotempest:
        CONFIG: osx_mpinompipython3.6.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpinompipython3.6.____cpythontempesttempest:
        CONFIG: osx_mpinompipython3.6.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpinompipython3.7.____cpythontempestnotempest:
        CONFIG: osx_mpinompipython3.7.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpinompipython3.7.____cpythontempesttempest:
        CONFIG: osx_mpinompipython3.7.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpinompipython3.8.____cpythontempestnotempest:
        CONFIG: osx_mpinompipython3.8.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpinompipython3.8.____cpythontempesttempest:
        CONFIG: osx_mpinompipython3.8.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpiopenmpipython3.6.____cpythontempestnotempest:
        CONFIG: osx_mpiopenmpipython3.6.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpiopenmpipython3.6.____cpythontempesttempest:
        CONFIG: osx_mpiopenmpipython3.6.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpiopenmpipython3.7.____cpythontempestnotempest:
        CONFIG: osx_mpiopenmpipython3.7.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpiopenmpipython3.7.____cpythontempesttempest:
        CONFIG: osx_mpiopenmpipython3.7.____cpythontempesttempest
        UPLOAD_PACKAGES: True
      osx_mpiopenmpipython3.8.____cpythontempestnotempest:
        CONFIG: osx_mpiopenmpipython3.8.____cpythontempestnotempest
        UPLOAD_PACKAGES: True
      osx_mpiopenmpipython3.8.____cpythontempesttempest:
        CONFIG: osx_mpiopenmpipython3.8.____cpythontempesttempest
        UPLOAD_PACKAGES: True

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)