# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-13
  strategy:
    matrix:
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.10.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.10.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.10.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.10.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.11.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.11.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.11.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.11.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.12.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.12.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.12.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.12.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.9.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.9.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2.0python3.9.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2.0python3.9.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2python3.13.____cp313tempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2python3.13.____cp313tempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpimpichnumpy2python3.13.____cp313tempesttempest:
        CONFIG: osx_64_hdf51.14.3mpimpichnumpy2python3.13.____cp313tempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.10.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.10.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.10.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.10.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.11.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.11.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.11.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.11.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.12.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.12.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.12.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.12.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.9.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.9.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2.0python3.9.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2.0python3.9.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2python3.13.____cp313tempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2python3.13.____cp313tempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpinompinumpy2python3.13.____cp313tempesttempest:
        CONFIG: osx_64_hdf51.14.3mpinompinumpy2python3.13.____cp313tempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.10.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.10.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.10.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.10.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.11.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.11.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.11.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.11.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.12.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.12.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.12.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.12.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.9.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.9.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.9.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2.0python3.9.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2python3.13.____cp313tempestnotempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2python3.13.____cp313tempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.3mpiopenmpinumpy2python3.13.____cp313tempesttempest:
        CONFIG: osx_64_hdf51.14.3mpiopenmpinumpy2python3.13.____cp313tempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.10.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.10.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.10.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.10.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.11.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.11.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.11.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.11.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.12.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.12.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.12.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.12.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.9.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.9.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2.0python3.9.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2.0python3.9.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2python3.13.____cp313tempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2python3.13.____cp313tempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpimpichnumpy2python3.13.____cp313tempesttempest:
        CONFIG: osx_64_hdf51.14.4mpimpichnumpy2python3.13.____cp313tempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.10.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.10.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.10.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.10.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.11.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.11.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.11.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.11.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.12.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.12.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.12.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.12.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.9.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.9.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2.0python3.9.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2.0python3.9.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2python3.13.____cp313tempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2python3.13.____cp313tempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpinompinumpy2python3.13.____cp313tempesttempest:
        CONFIG: osx_64_hdf51.14.4mpinompinumpy2python3.13.____cp313tempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.10.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.10.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.10.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.10.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.11.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.11.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.11.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.11.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.12.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.12.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.12.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.12.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.9.____cpythontempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.9.____cpythontempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.9.____cpythontempesttempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2.0python3.9.____cpythontempesttempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2python3.13.____cp313tempestnotempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2python3.13.____cp313tempestnotempest
        UPLOAD_PACKAGES: 'True'
      osx_64_hdf51.14.4mpiopenmpinumpy2python3.13.____cp313tempesttempest:
        CONFIG: osx_64_hdf51.14.4mpiopenmpinumpy2python3.13.____cp313tempesttempest
        UPLOAD_PACKAGES: 'True'
    maxParallel: 25
  timeoutInMinutes: 360
  variables: {}

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
      export remote_url=$(Build.Repository.Uri)
      export sha=$(Build.SourceVersion)
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
        export IS_PR_BUILD="True"
      else
        export IS_PR_BUILD="False"
      fi
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)